### ISSUE TITLE
Use post-root-package-install to trigger the installer only once?

### ISSUE THREAD

**Issue by xtreamwayz** [xtreamwayz/expressive-composer-installer#1]
I've been playing a bit more with the installer and it seems to work nicely. The only annoyance I found is that the installer is always triggered on ``composer update`` and ``composer install``. Personally I think that it should ask for user input only the first time or when forced by the user. Obviously you don't want to mess up a project that's already in production by suddenly changing a dependency.

## Trigger only once

If the project is installed via ``composer create-project`` there is an event which can be used.

> **post-root-package-install:** occurs after the root package has been installed, during the create-project command.

By hooking up to this event you make sure the installer runs only once. However it won't run when user download the package and use the ``install`` or ``update`` commands.

## Option to force installer

For the user triggered option this will be an issue. I haven't found an option for custom parameters like ``--reset-project``. What I can do is save the user selections to composer.json instead of a file in the Installer.php dir. Then the installer will only run if all or maybe one of the options is missing.

Storing the user selections in composer.json makes also sure that it is distributed with the created project. Right now the settings are not included in git. Personally I think you want to have it stored and distributed with git since you are building a project with those selected options.

Adding an option like ``--reset-project`` might be possible by using the ``command`` event but I need to look into that.

> **command:** occurs before any Composer Command is executed on the CLI. It provides you with access to the input and output objects of the program.

## Remove scripts after execution

Another option is to unregister itself from the composer scripts. However you can't run it again.

Composer events:
- post-root-package-install: triggered on ``create-project``
- pre-install-cmd: triggered on ``install`` and right after a post-root-package-install event when creating a package
- pre-update-cmd: triggered on ``update``

So I guess the question is how many times to run the installer.

/cc @weierophinney

**Comment by xtreamwayz** [comment]
@weierophinney I've just update a lot of code. Personally I prefer to ask the questions only once for reasons mentioned above. If you think it should be different, please let me know.

**Comment by weierophinney** [comment]
@xtreamwayz Sorry for the late reply; busy weekend, and then was ill yesterday.

I agree - the installer should only ever be run once, on first install or update. After that, we should assume the developer has answered the questions, allowing for unattended install.

**Comment by xtreamwayz** [comment]
@weierophinney I've made some changes yesterday and this is basically how it works now. It checks for missing answers and keeps asking a question until it's answered. If an answer is given it adds the package and copies config files if needed.

However it keeps running on every update / install and checks for unanswered questions. The only thing I can add is that it completely removes itself from ``composer.json -> scripts`` if all answers are answered. This way if someone messes up the settings in ``composer.json -> extra`` it won't run again.

For the rest I think it's pretty much feature complete and everything else is most likely overkill.
