### ISSUE TITLE
Refactor config loader (config.php)

### ISSUE THREAD

**Issue by xtreamwayz** [xtreamwayz/expressive-composer-installer#15]
I've been playing with zend-servicemanager 3 and it works great. However to be have a configuration that is compatible between all containers is a bit troublesome. Right now the config is loaded in ``config.php`` from ``container.php``.

For zend service-manager 3 you need something like this to it working:

```php
<?php

use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\Factory\InvokableFactory;

// Load configuration
$config = require 'config.php';
$dependencies = $config['dependencies'];

// Inject config as a service
$dependencies['services']['config'] = $config;

foreach ($config['dependencies']['invokables'] as $invokable => $factory) {
    if ($invokable != $factory) {
        $dependencies['aliases'][$invokable] = $factory;
    }

    $dependencies['factories'][$factory] = InvokableFactory::class;
}
unset($dependencies['invokables']);

// Build container
$container = new ServiceManager($dependencies);

return $container;
```

Another issue is that it is not easily cachable. Ideally you want to cache it inside ```config.php```. I'm just wondering what would be the right direction to go. Maybe built around servicemanager 3 and convert it back to other containers?

Another direction to go would be to build config files during installation. (Right now they are copied.) I've been thinking about this before but a config builder class needs to be included in the source since we can't depend on external packages and classes. The main advantage is that optimized config files can be written for each container package, using best practices. No conversion hacks required.

Any thoughts about this?

ping: @weierophinney

**Comment by weierophinney** [comment]
First, servicemanager v3 now understands the "invokables" key, so you don't need too do that bit of work from your example above. The only difference between v2 and v3 is how you pass the configuration to the instance at this point.

In terms of caching, I'd argue that could be done by a build-time tool. In development, you want to recognize and act on changes immediately, but when pushing to production, you can cache, optimize, etc. and replace the `config.php` file with those results.

In terms of building config files during installation vs. copying, I'm afraid I'm not following. Can you maybe detail the new process a bit more, showing both the why and how?

BTW, I'm about to fork this into the zendframework org, FINALLY. :) Thanks for the great work, @xtreamwayz !

**Comment by xtreamwayz** [comment]
@weierophinney If ZF3 understands invokables now then forget about what I was saying and keep it simple. Caching the config will do just fine.
