### ISSUE TITLE
Add more container-interop containers

### ISSUE THREAD

**Issue by xtreamwayz** [xtreamwayz/expressive-composer-installer#5]
# TODO

- [x] Add mouf/pimple-interop container
- [x] Add aura/di:3.0.*@beta container

**Comment by xtreamwayz** [comment]
@weierophinney Looking at the docs I guess there is no easy way to configure pimple-interop and aura/di with an array?

**Comment by weierophinney** [comment]
But that I'm aware of, unfortunately. We may eventually provide packages
for doing so.

**Comment by xtreamwayz** [comment]
@weierophinney Containers added. Ready for testing.
