### ISSUE TITLE
Some zend-view plugins are not working

### ISSUE THREAD

**Issue by xtreamwayz** [xtreamwayz/expressive-composer-installer#6]
Some plugins are missing dependencies. Like the Zend\View\Helper\Url needs a router to resolve named routes.

**Comment by weierophinney** [comment]
I don't think `Zend\View\Helper\Url` will work with zend-expressive, actually, *unless* you're using the zend-mvc router. If you're not, you would need to have an alternate helper that utilizes the `RouterInterface::generateUrl()` method. That said: we should likely supply that view helper!

Another candidate would be the ServerUrl helper, as it relies on the zend-http request object and/or superglobals to do its work.

Could you open issues on zend-expressive? That's likely the better location for dealing with them.

Thanks, @xtreamwayz !

**Comment by xtreamwayz** [comment]
Opened a new issue here: zendframework/zend-expressive#123
